### ISSUE TITLE
[Improvement] Channels without scrollbars should stick messages to the top

### ISSUE THREAD

**Issue by Diyamund** [XYZenix/DTM-16#4]
```css
.scrollerContent-WzeG7R {
    justify-content: normal;
}
```
![image](https://user-images.githubusercontent.com/44238627/126255326-16cab1df-7db3-4ed7-bd66-5fab4e5ed9d2.png)
Messages in 2019 (and possibly earlier) that are smaller than your screen used to stick to the top.
The CSS provided implements this in modern Discord.
